name: è·å–migu_epg

on:
  schedule:
    - cron: '0 20 * * *'  # æ¯å¤© UTC æ—¶é—´ 1:00 æ‰§è¡Œï¼Œå³åŒ—äº¬æ—¶é—´ 9:00

  workflow_dispatch:  # æ‰‹åŠ¨è§¦å‘

jobs:
  epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. å®‰è£… PHP + Composer
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'                  # ğŸ”§ æ”¹ç‰ˆæœ¬
          extensions: mbstring,intl
          ini-values: date.timezone=Asia/Shanghai
          tools: composer

      # 3. è£…ä¾èµ–ï¼ˆå¦‚ä¸éœ€è¦å¯åˆ æ‰ï¼‰
      #- name: Composer install
        #run: composer install --no-progress --prefer-dist

      - name: è¿è¡Œè„šæœ¬
        run: |
          php jiaoben/epg_migu.php

      - name: Check workspace and epg directory
        run: |
          echo "Current workspace: $GITHUB_WORKSPACE"
          ls -la $GITHUB_WORKSPACE/epg/

      - name: ç¼“å­˜è¿è¡Œç»“æœ
        uses: actions/upload-artifact@v4
        with:
          name: cache
          path: $GITHUB_WORKSPACE/epg/
          
      - name: æäº¤æ›´æ–°
        run: |
          cd $GITHUB_WORKSPACE/epg/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update xmigu epg"
          git push
